### ISSUE TITLE
futureporn-scout crashes 5 minutes after end of stream

### ISSUE THREAD

**Issue by insanity54** [insanity54/futureporn#206]
This occured near start of a mel stream. there were 2 stop events before a start event. I think the end of stream timer got kicked off, and 5 minutes later, crash.

```
file:///home/chris/Documents/futureporn-scout/src/Stream.js:102
    const statement = this.appContext.db.prepare(``)
                                      ^

TypeError: Cannot read properties of undefined (reading 'db')
    at Stream.getChat (file:///home/chris/Documents/futureporn-scout/src/Stream.js:102:39)
    at createStreamVOD (file:///home/chris/Documents/futureporn-scout/src/cbCallbacks.js:95:10)
    at Timeout._onTimeout (file:///home/chris/Documents/futureporn-scout/src/cbCallbacks.js:84:62)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.15.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by insanity54** [comment]
I disabled the timers to work around this issue. This means that I need to manually process the vod when it is completed. Later on I will revisit the timers to improve automation. Right now, I'm focusing on capture reliability.
