### ISSUE TITLE
futureporn-scout can't handle passworded rooms

### ISSUE THREAD

**Issue by insanity54** [insanity54/futureporn#218]
observed behavior is that futureporn-scout crashes when a room has a pw

```
file:///home/chris/Documents/futureporn-scout/src/Room.js:70
    if (!rawScript) throw new Error('window.initialRoomDossier is null. This could mean the channel is in password mode')
                          ^

Error: window.initialRoomDossier is null. This could mean the channel is in password mode
    at Room.getInitialRoomDossier (file:///home/chris/Documents/futureporn-scout/src/Room.js:70:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Room.getRoomId (file:///home/chris/Documents/futureporn-scout/src/Room.js:261:20)
    at async Room.getPushServiceAuth (file:///home/chris/Documents/futureporn-scout/src/Room.js:223:19)
    at async Room.monitorRealtime (file:///home/chris/Documents/futureporn-scout/src/Room.js:132:55)

Node.js v18.16.0
 ELIFECYCLE  Command failed with exit code 1.
```

expected behavior is that futureporn-scout tries again later in this case

**Comment by insanity54** [comment]
graceful handling is added
